### ISSUE TITLE
Looking for "Ground Truth"

### ISSUE THREAD

**Issue by edgarfelizmenio** [LieberInstitute/HumanPilot#10]
Hello, I am currently exploring the dataset for a project that I am doing but I can't seem to find a comprehensive documentation on the available data. I am specifically looking for the ground truth but I am not quite sure if I can use ```layer_guess```.

Any help would be appreciated.

Thanks!

**Comment by lcolladotor** [comment]
Hi @edgarfelizmenio,

The manual annotations are in the `spe$spatialLIBD` as well as `layer_guess` (and a few other related names). As for documentation, it's available at http://spatial.libd.org/spatialLIBD/ as well as 
https://github.com/LieberInstitute/spatialLIBD/blob/devel/inst/app/www/documentation_spe.md#common-options.

<img width="304" alt="Screenshot 2024-07-23 at 3 30 04 PM" src="https://github.com/user-attachments/assets/600d574d-da06-4a4a-8a49-d9368c7639a1">

<img width="1286" alt="Screenshot 2024-07-23 at 3 30 10 PM" src="https://github.com/user-attachments/assets/a3f93680-f726-4fc4-b80a-f82aa7c6bc94">


Best,
Leonardo
