### ISSUE TITLE
homology analyses of previous marker genes

### ISSUE THREAD

**Issue by andrewejaffe** [LieberInstitute/HumanPilot#2]
can you take the genes in the previous layer marker table, and make a boxplot of mean expression in brainseq phase2 DLPFC, within fetal and then adult? ie 4 boxes: fetal:layerMarker, fetal:notLayerMarker, adult:layerMarker, adult:nonLayerMarker (where there are way more points in the nonLayerMarker boxes)

**Comment by lcolladotor** [comment]
I didn't remember this issue from about a year ago. We could check this with @abspangler13.

**Comment by lcolladotor** [comment]
I closed it due to inactivity.
