### ISSUE TITLE
Images quiality

### ISSUE THREAD

**Issue by Svvord** [LieberInstitute/HumanPilot#5]
There are quality problems with pathology images, and noise that should not be present can be seen when the original image is enlarged. Are there no high quality pathology images available for download? Or ISH images.

**Comment by lcolladotor** [comment]
Check the `image_hi` column at https://github.com/LieberInstitute/HumanPilot#raw-data. Each of these images are like 500 mb each. Though well, in our newer studies we have generated higher quality images than the ones from this pilot study.
