### ISSUE TITLE
Spatially-registered DLPFC snRNA-seq data from paper?

### ISSUE THREAD

**Issue by bhavyaac** [LieberInstitute/HumanPilot#6]
Hello! Thank you for your great work on this package. I found it very easy to use and your documentation is excellent. I have a question regarding the data availability from your paper. 
In your paper (Maynard et al 2021 Nat. Neurosci), you spatially registered three independent snRNA-seq datasets, and one of these datasets was generated by your research team. I am wondering whether this annotated snRNA-seq dataset is publicly available. (From my understanding, the raw data provided at the Globus link is Visium data only, and the data which is available for download through the `spatialLIBD` package is also Visium-based.) Please let me know if there is any way I can access this data. Thank you!

**Comment by serenolopezdarwin** [comment]
The DLPFC data can be found in here:

https://github.com/LieberInstitute/10xPilot_snRNAseq-human
