### ISSUE TITLE
Multiple samples in a layer guess file

### ISSUE THREAD

**Issue by chaichontat** [LieberInstitute/HumanPilot#7]
The layer guess file for samples `151507` and `151669`

https://github.com/LieberInstitute/HumanPilot/blob/89e9002790a8b78c8c7ce06f5331809626386fd5/Analysis/Layer_Guesses/First_Round/spatialLIBD_layerGuesses_2019-12-19%2015_55_14_151507.csv#L4221-L4224

https://github.com/LieberInstitute/HumanPilot/blob/89e9002790a8b78c8c7ce06f5331809626386fd5/Analysis/Layer_Guesses/First_Round/spatialLIBD_layerGuesses_2019-12-19%2016_10_07_151669.csv#L4221-L4224

contain multiple samples.

**Comment by lcolladotor** [comment]
Yes, that's how they were built with `spatialLIBD`. Hence why the files include a sample ID column.
