### ISSUE TITLE
how to donwload fastq/bam data on blobus

### ISSUE THREAD

**Issue by JunMa11** [LieberInstitute/HumanPilot#8]
Dear spatialLIBD team,

Thanks for sharing the awesome resources. 

I'd like to download the fastq/bam files from http://research.libd.org/globus/

I log in to the platform but the download button is gray. 

![image](https://user-images.githubusercontent.com/19947331/231770414-295b2ff9-f617-469d-8226-c46a8a853c8f.png)

Then, I click on `Transfer or Sync to ...` and the `start` button but it still doesn't work. Do I miss anything? Any comments are highly appreciated:)

![image](https://user-images.githubusercontent.com/19947331/231770565-d85ecd22-83e5-4c8b-ad7b-a124ed831865.png)

**Comment by lcolladotor** [comment]
Hi!

Thank you for your interest in our work. From your last screenshot I see that you haven't logged in to your own system yet to determine the transfer destination. You can see that it says "search" on the top right. You have to search for your own Globus destination first. For us, that would be searching for "jhpce#globus01". Check with your HPC system administrators for the name you should search. Once you have logged in into your HPC system, and chosen a directory where you want to transfer the files, you'll be able to start this transfer.

While this information is specific to JHPCE https://jhpce.jhu.edu/knowledge-base/using-globus-to-transfer-files/, some of its contents might be useful to you.

Best,
Leo

**Comment by JunMa11** [comment]
Hi @lcolladotor ,

It seems that Globus has been down for multiple days. Is there any way to fix this issue?

![Screenshot 2023-05-01 at 3 55 36 PM](https://user-images.githubusercontent.com/19947331/235520268-fc658d4b-f044-4507-bb86-1e287aa656ac.png)

**Comment by lcolladotor** [comment]
Hi @JunMa11,

JHPCE (the data host) is under active planned maintenance. Supposedly it'll be back online later this week. I'll update you here once JHPCE is back online (@Nick-Eagles @RyAMiller or others could do it too if I'm unavailable). 

This is a separate issue from the one you initially reported.

Best,
Leo

**Comment by lcolladotor** [comment]
> Dear JHPCE Community,
> The JHPCE cluster is now back online.

=)

**Comment by JunMa11** [comment]
Hi @lcolladotor ,

It works now. Thanks for your great help very much.

**Comment by lcolladotor** [comment]
Awesome! Have fun with the data =)
