### ISSUE TITLE
Error in `collect()`: ! Failed to collect lazy table.

### ISSUE THREAD

**Issue by FAFUshiyan** [LieberInstitute/HumanPilot#9]
Dear spatialLIBD team,
I have completed the installation of spatialLIBD, but when executing spe <- fetch_data(type = "spe"), an error occurred. The error message is as follows:
<img width="679" alt="image" src="https://github.com/LieberInstitute/HumanPilot/assets/76734644/ce9b600d-918d-4b06-95f4-bc90becaea3d">

I would like to understand the cause of this error.

**Comment by lcolladotor** [comment]
See https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834717960 and https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834718947. In particular https://github.com/Bioconductor/BiocFileCache/pull/50#issuecomment-1781113054.

We would need to have your R session information output to help you further to check that the R package versions you are using are up to date.

Best,
Leo

**Comment by CSQxiaogongju** [comment]
> See [lmweber/WeberDivechaLCdata#1 (comment)](https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834717960) and [lmweber/WeberDivechaLCdata#1 (comment)](https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834718947). In particular [Bioconductor/BiocFileCache#50 (comment)](https://github.com/Bioconductor/BiocFileCache/pull/50#issuecomment-1781113054).
> 
> We would need to have your R session information output to help you further to check that the R package versions you are using are up to date.
> 
> Best, Leo

Hi Leo:
I meet the same problem. my R version is 4.3.1 and BiocManager is 1.30.22
Best,
Siqi

**Comment by CSQxiaogongju** [comment]
> > See [lmweber/WeberDivechaLCdata#1 (comment)](https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834717960) and [lmweber/WeberDivechaLCdata#1 (comment)](https://github.com/lmweber/WeberDivechaLCdata/issues/1#issuecomment-1834718947). In particular [Bioconductor/BiocFileCache#50 (comment)](https://github.com/Bioconductor/BiocFileCache/pull/50#issuecomment-1781113054).
> > We would need to have your R session information output to help you further to check that the R package versions you are using are up to date.
> > Best, Leo
> 
> Hi Leo: I meet the same problem. my R version is 4.3.1 and BiocManager is 1.30.22 Best, Siqi

I success to solve the problem when I update the Bioconductor to 3.18
